# Generated by Django 5.2.1 on 2025-06-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='jenis_id',
        ),
        migrations.RemoveField(
            model_name='barang',
            name='waktu_post',
        ),
        migrations.DeleteModel(
            name='Jenis',
        ),
    ]
