# Generated by Django 5.2.1 on 2025-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
